version: "3"
services:
  server-k8s:
    container_name: "server"
    build:
      context: .
      dockerfile: ./server/Dockerfile-k8s
    environment:
      - COGNITO_USER_POOL_ID=asdf
      - COGNITO_APP_CLIENT_ID=asdf
      - SESSION_NAME=asdf
      - SESSION_SECRET=asdf
      - DATABASE_URL=postgres://admin:pass@postgres_test:5432/boptestdb
      - SUPER_USERS=email1@email.com,email2@email.com,email3@email.com
      - CONTEXT=testing
    ports:
      - "8080:8080"
    depends_on:
      - pg
    volumes:
      - staticfiles:/usr/client/build
    command: "npm run start:dev"
  pg:
    image: "postgres"
    container_name: "postgres"
    # port on host : port in Docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "boptestdb"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data:z
  client-k8s:
    container_name: "client"
    build:
      context: .
      dockerfile: ./client/Dockerfile-k8s
    volumes:
      - ./client/src:/usr/client/src:z
      - staticfiles:/usr/client/build
volumes:
  staticfiles:
