# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      -  '*'
  push:
    branches:
      -  '*'
    tags:
      - '*'
    
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Backend Tests
        env:
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
          SESSION_NAME: ${{ secrets.SESSION_NAME }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: docker-compose -f test-conf.yml down -v && docker-compose -f test-conf.yml run api_test && docker-compose -f test-conf.yml down -v

      - name: Build K8s containers
        run: docker-compose -f docker-compose-k8s.yml build

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Publish docker images to Docker Hub
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/master' ||
          contains(github.ref, 'refs/tags') 
        shell: bash
        run: ci/publish_to_docker.sh
